- name: create service config dir
  file:
    path: /usr/local/adbot/{{instance_name}}/config
    owner: adbot
    group: adbot
    state: directory
  tags:
    - upgrade
- name: copy service config file 
  template:
    src: roles/laser_control/templates/config.yml
    dest: /usr/local/adbot/{{instance_name}}/config/config.yml
    owner: adbot
    group: adbot
    mode: 0644
  tags:
    - upgrade
- name: create ansible roles dir
  file:
    path: /usr/local/adbot/{{instance_name}}/ansible/roles
    owner: adbot
    group: adbot
    state: directory
  tags:
    - upgrade
- name: copy playbook roles
  copy:
    src: "{{ item }}"
    dest: /usr/local/adbot/{{instance_name}}/ansible/roles
    mode: 0644
  with_items:
    - roles/service
    - roles/laser_data_cleaner
    - roles/ramdisk
  tags:
    - upgrade
    - copy_roles
