debug: true
http:
  port: {{http_port}}
  host: {{ansible_default_ipv4.address}}
static:
  root: /usr/local/adbot/{{instance_name}}/{{package_tag}}/
database:
  driver: {{db_driver}}
  dsn: {{dsn}}
logger:
  level: debug
  fileName: /usr/local/adbot/{{instance_name}}/logs/service.log
  maxSize: 1024
  maxBackups: 3
  maxAge: 7
  compress: true
auth:
  sessionSaveSeconds: 86400
consul:
  address: {{consul_address}}
  token: {{consul_token}}
cluster:
  serviceName: {{service_name}}
  proxyServiceName: {{proxy_service_name}}
project:
  projectName: {{project_name}}
laserClient:
  timeoutMs: {{laser_client_timeout}}
batchUpdateManager:
  url: {{batch_manager_url}}
ansible:
  sshPort: 30022
  playbookDir: /usr/local/adbot/{{instance_name}}/ansible
  tmpHostFile: hosts
  tmpPlaybookFile: playbook.yml
email:
  emailUser: {{email_user}}
  emailPassword: {{email_password}}
  emailSnmpAddress: {{email_smtp_address}}
  emailFrom: {{email_from}}
report:
  cronExpressionPeak: "0 0 23 * * *"
  cronExpressionPeacePeak: "0 0 12 * * * *"
prometheus:
  serverPrometheusAddress: {{running_info_prometheus}}
  clientPrometheusAddress: {{machine_info_prometheus}}
commonUrls:
  - /database/list
  - /keycheck/list
  - /version_change/show
  - /table/list
  - /table/list_commands
  - /ticket/store
  - /ticket/list
  - /ticket/update
  - /user/info
  - /config_validator/unsynchronized_config
adminUsers:
  - admin
laserCommands:
  singleOperations:
    - get
    - set
    - expire
    - expireAt
    - ttl
    - append
    - setx
    - exist
    - hget
    - hgetall
    - hexists
    - hkeys
    - hlen
    - hmget
    - hset
    - hmset
    - hdel
    - decr
    - incr
    - decrBy
    - incrBy
    - lindex
    - llen
    - lpop
    - lpush
    - lrange
    - rpop
    - rpush
    - sadd
    - sismember
    - sremove
    - smembers
    - zadd
    - zrangeByScore
    - zremRangeByScore
  multipleOperations:
    - mset
    - mget
    - msetDetail
    - mgetDetail
