load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "ip",
    srcs = ["ip.go"],
    importpath = "github.com/algo-data-platform/LaserDB/sdk/go/common/ip",
    visibility = ["//visibility:public"],
)
