version: "3"

services:
  consul:
    image: consul
    container_name: consul
    ports:
      - "8500:8500"
    environment:
      CONSUL_LOCAL_CONFIG: '{ "disable_update_check": true }'
    command: "agent -server -data-dir=/tmp/consul -client=0.0.0.0 -bootstrap -bind=172.16.1.2 -ui"
    restart: always
    networks:
      internal:
        ipv4_address: 172.16.1.2

  mysql:
    image: mysql
    container_name: mysql
    networks:
      internal:
        ipv4_address: 172.16.1.3
    environment:
      MYSQL_ROOT_PASSWORD: root
    command: "--default-authentication-plugin=mysql_native_password"
    restart: always
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d

  prometheus:
    image: prom/prometheus:v2.14.0
    container_name: prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - 9090:9090
    restart: always
    networks:
      internal:
        ipv4_address: 172.16.1.4

  grafana:
    image: grafana/grafana
    container_name: grafana
    user: "104"
    depends_on:
      - prometheus
    restart: always
    ports:
      - 3000:3000
    networks:
      internal:
        ipv4_address: 172.16.1.5

  laser_leader:
    image: laserdb/laserdb
    container_name: laser_leader
    ports:
      - 10022:10022
      - 20022:20022
    environment:
      LASER_HOST: 172.16.1.6
      LASER_GROUP_NAME: default
      LASER_NODE_ID: 1
      LASER_PORT: 20022
      LASER_HTTP_PORT: 10022
      LASER_SERVICE_NAME: laser_test
    depends_on:
      - consul
    restart: always
    networks:
      internal:
        ipv4_address: 172.16.1.6

  laser_follower:
    image: laserdb/laserdb
    container_name: laser_follower
    ports:
      - 10023:10023
      - 20023:20023
    environment:
      LASER_HOST: 172.16.1.7
      LASER_GROUP_NAME: default
      LASER_NODE_ID: 2
      LASER_PORT: 20023
      LASER_HTTP_PORT: 10023
      LASER_SERVICE_NAME: laser_test
    depends_on:
      - consul
    restart: always
    networks:
      internal:
        ipv4_address: 172.16.1.7

  laser_proxy:
    image: laserdb/laser_proxy
    container_name: laser_proxy
    ports:
      - 16382:16382
      - 10024:10024
    environment:
      LASER_PROXY_HOST: 172.16.1.8
      LASER_PROXY_PORT: 16382
      LASER_PROXY_HTTP_PORT: 10024
      LASER_PROXY_TARGET_SERVICE_NAME: laser_test
      LASER_PROXY_SERVICE_NAME: laser_test_proxy
    depends_on:
      - consul
      - laser_leader
      - laser_follower
    restart: always
    networks:
      internal:
        ipv4_address: 172.16.1.8

  laser_control:
    image: laserdb/laser_control
    container_name: laser_control
    ports:
      - 31000:31000
    depends_on:
      - consul
      - mysql
    command:
      [
        "/wait-for-it.sh",
        "-t",
        "0",
        "mysql:3306",
        "--",
        "/laser/control/laser_control",
        "server",
        "--config=/laser/control/etc/config.yaml",
      ]
    restart: always
    networks:
      internal:
        ipv4_address: 172.16.1.9

networks:
  internal:
    ipam:
      driver: default
      config:
        - subnet: 172.16.1.0/24
