# laser batch update manager上线更新启动
- hosts: laser_batch_update_manager_demo
  vars:
    package_tag: 'v1.0.1'
    package_name: 'laser_batch_update_manager'
    instance_name: 'laser_batch_update_manager_demo'
    start_options: "--spring.config.location=/usr/local/adbot/{{instance_name}}/config/application.properties --logging.config=/usr/local/adbot/{{instance_name}}/config/log4j2.properties"
    service_env: 'default'
    service_file: 'java-jar'
    ad_core_user: "adbot"
    ad_core_group: "adbot"
    other_env: "JAVA_HOME=\"/usr/local/jdk1.8.0_131\""
    http_port: '8080'
    hdfs_base_path: '/dw_ext/ad/ads_core/laser'
    hdfs_sub_path: 'demo'
    hdfs_import_type: 'base'
    hdfs_hadoop_config_path: '/usr/local/hadoop-2.7.3/etc/hadoop/core-site.xml,/usr/local/hadoop-2.7.3/etc/hadoop/hdfs-site.xml'
    laser_monitor_task_cron: '0 */1 * * * *'
    laser_dingding_task_cron: '0 0 23 * * *'
    checksum_monitor_task_cron: '0 */1 * * * *'
    dingding_enable: false
    dingding_secret: xxxx
    dingding_token: xxxxxx
    logging_config: 'classpath:log4j2.properties'

    rootLogger_level: 'info'
    appender_rolling_fileName: '/usr/local/adbot/{{instance_name}}/logs/{{package_name}}.log'
    appender_rolling_filePattern: '/usr/local/adbot/{{instance_name}}/logs/{{package_name}}%d{yyyy-MM-dd}_%i.log'
    appender_console_layout_pattern: "%d{MM-dd HH:mm:ss.SSS } [%5p] [%40.40c{1.}:%3L] - %m%n"
    appender_rolling_layout_pattern: "%d{MM-dd HH:mm:ss.SSS } [%5p] [%40.40c{1.}:%3L] - %m%n"

  roles:
    - service
    - laser_batch_update
