# laser control demo 部署配置
- hosts: laser_demo_control
  vars:
    package_tag: 'v1.0.1'
    package_name: 'laser_control'
    service_name: 'demo'
    proxy_service_name: 'demo_proxy'
    project_name: 'test'
    http_port: '8088'
    instance_name: 'laser_demo_control'
    start_options: " server --config=/usr/local/adbot/{{instance_name}}/config/config.yml"
    service_env: 'default'
    db_driver: sqlite3
    dsn: /usr/local/adbot/{{instance_name}}/laser_control.db
    consul_address: '127.0.0.1:8500'
    consul_token: 'your_consul_token'
    email_user: email_user
    email_password: email_password
    email_smtp_address: 127.0.0.1:25
    email_from: noreply@demo.example.com
    running_info_prometheus: 127.0.0.1:9909
    machine_info_prometheus: 127.0.0.1:9009
    laser_client_timeout: 10000
    batch_manager_url: 'http://127.0.0.1:8080'
    other_env: 'ANSIBLE_HOST_KEY_CHECKING=False'
  roles:
    - laser_control
    - service
