package lib

import (
	"testing"

	"github.com/stretchr/testify/assert"
)

type uc struct {
	dbname string
	tbname string
	pk     string // primaryKey
	pid    uint32 // partitionId
	sid    uint64 // shardId
}

var (
	useCases = []uc{
		uc{
			dbname: "zijumnojsb",
			tbname: "pieil",
			pk:     "vjphkckl",
			pid:    19,
			sid:    25,
		},
		uc{
			dbname: "swnzocmtfz",
			tbname: "iwqtn",
			pk:     "nmkgcnyy",
			pid:    0,
			sid:    22,
		},
		uc{
			dbname: "mpqebywyyl",
			tbname: "iuzqr",
			pk:     "dfnqqibz",
			pid:    22,
			sid:    3,
		},
		uc{
			dbname: "txzfnjlgev",
			tbname: "uawmy",
			pk:     "dyjvlxmq",
			pid:    6,
			sid:    14,
		},
		uc{
			dbname: "vaqgnylcjr",
			tbname: "igxfj",
			pk:     "afjsvmcl",
			pid:    10,
			sid:    22,
		},
		uc{
			dbname: "fvfcqjtqbw",
			tbname: "ifubm",
			pk:     "avqptjmr",
			pid:    1,
			sid:    0,
		},
		uc{
			dbname: "xhylrscrrc",
			tbname: "unknv",
			pk:     "ifcwvxbp",
			pid:    30,
			sid:    29,
		},
		uc{
			dbname: "mfhzebqctz",
			tbname: "rorna",
			pk:     "myqbohxv",
			pid:    22,
			sid:    8,
		},
		uc{
			dbname: "ayjauuiivy",
			tbname: "fjnwu",
			pk:     "mqceaast",
			pid:    16,
			sid:    4,
		},
		uc{
			dbname: "qebxktpomu",
			tbname: "bhihp",
			pk:     "twmdnesg",
			pid:    7,
			sid:    13,
		},
		uc{
			dbname: "yzybbuksia",
			tbname: "tciyy",
			pk:     "rpvrczyg",
			pid:    18,
			sid:    1,
		},
		uc{
			dbname: "ekjvitoggh",
			tbname: "ghjai",
			pk:     "epkajybx",
			pid:    3,
			sid:    26,
		},
		uc{
			dbname: "menjbrumak",
			tbname: "hcfyw",
			pk:     "vtusjhak",
			pid:    13,
			sid:    2,
		},
		uc{
			dbname: "ghbojxklzk",
			tbname: "hxkgp",
			pk:     "qazxwawx",
			pid:    11,
			sid:    17,
		},
		uc{
			dbname: "dexlgigwfw",
			tbname: "elwuf",
			pk:     "kgmhnire",
			pid:    21,
			sid:    22,
		},
		uc{
			dbname: "mcvnovsesl",
			tbname: "jrijh",
			pk:     "vlciffle",
			pid:    8,
			sid:    30,
		},
		uc{
			dbname: "fdqofkbovw",
			tbname: "upjgo",
			pk:     "zozbgwcn",
			pid:    14,
			sid:    32,
		},
		uc{
			dbname: "pnelkmtxkd",
			tbname: "sgtqn",
			pk:     "dcuauvxp",
			pid:    7,
			sid:    17,
		},
		uc{
			dbname: "jzwprpmwrn",
			tbname: "zmkxy",
			pk:     "irkloynm",
			pid:    26,
			sid:    1,
		},
		uc{
			dbname: "exetrszpjt",
			tbname: "nisds",
			pk:     "aadzaasr",
			pid:    2,
			sid:    27,
		},
		uc{
			dbname: "kyhqkgmocq",
			tbname: "racbs",
			pk:     "ipaxasgt",
			pid:    31,
			sid:    16,
		},
		uc{
			dbname: "xodrvpcqch",
			tbname: "ivnju",
			pk:     "ngcqexfp",
			pid:    17,
			sid:    0,
		},
		uc{
			dbname: "rkjlwyiasa",
			tbname: "lgltn",
			pk:     "traelnit",
			pid:    32,
			sid:    10,
		},
		uc{
			dbname: "nyrqemmzpt",
			tbname: "egert",
			pk:     "zrqfmexp",
			pid:    14,
			sid:    5,
		},
		uc{
			dbname: "rpqdpdnulz",
			tbname: "ylfmp",
			pk:     "gtcnbwue",
			pid:    14,
			sid:    21,
		},
		uc{
			dbname: "oznducoato",
			tbname: "elspy",
			pk:     "wwaoslkt",
			pid:    12,
			sid:    22,
		},
		uc{
			dbname: "gveavpigvv",
			tbname: "vltoq",
			pk:     "fgtpjogo",
			pid:    27,
			sid:    19,
		},
		uc{
			dbname: "gyxgebazkt",
			tbname: "bhmgk",
			pk:     "gggafkve",
			pid:    2,
			sid:    16,
		},
		uc{
			dbname: "psluxmyljb",
			tbname: "zrapq",
			pk:     "rvzxsbxa",
			pid:    22,
			sid:    29,
		},
		uc{
			dbname: "jrccijqbpz",
			tbname: "rspky",
			pk:     "ixttdsqf",
			pid:    6,
			sid:    17,
		},
		uc{
			dbname: "petkvrzlyb",
			tbname: "cpzik",
			pk:     "aprnrggi",
			pid:    18,
			sid:    4,
		},
		uc{
			dbname: "cbkmteguuo",
			tbname: "hbsww",
			pk:     "tgrgqlvp",
			pid:    24,
			sid:    22,
		},
		uc{
			dbname: "qzxkydnzfr",
			tbname: "fsunv",
			pk:     "sdoqanfm",
			pid:    15,
			sid:    28,
		},
		uc{
			dbname: "kqthtjlzft",
			tbname: "warzt",
			pk:     "vxxoivtk",
			pid:    8,
			sid:    17,
		},
		uc{
			dbname: "dapunoorne",
			tbname: "pmzpt",
			pk:     "weslpwtd",
			pid:    2,
			sid:    8,
		},
		uc{
			dbname: "lqykdohcaj",
			tbname: "egtej",
			pk:     "dvgfyaje",
			pid:    15,
			sid:    27,
		},
		uc{
			dbname: "mqljobsktm",
			tbname: "udszw",
			pk:     "ivqcmuaq",
			pid:    30,
			sid:    11,
		},
		uc{
			dbname: "mdirjuanwr",
			tbname: "sxcie",
			pk:     "vgliktmg",
			pid:    2,
			sid:    0,
		},
		uc{
			dbname: "wxyrkrurec",
			tbname: "kljfv",
			pk:     "ovaaluww",
			pid:    8,
			sid:    7,
		},
		uc{
			dbname: "zdoeoepiqa",
			tbname: "wldii",
			pk:     "ylfqemdw",
			pid:    30,
			sid:    8,
		},
		uc{
			dbname: "iyclrsqdfc",
			tbname: "bettg",
			pk:     "zizhapws",
			pid:    15,
			sid:    18,
		},
		uc{
			dbname: "nfhdqzlphc",
			tbname: "jpsxv",
			pk:     "fijtmmiw",
			pid:    16,
			sid:    30,
		},
		uc{
			dbname: "yzrrdwkkqh",
			tbname: "vlxyi",
			pk:     "eldpteka",
			pid:    25,
			sid:    20,
		},
		uc{
			dbname: "sekzkfsrxa",
			tbname: "fdhvb",
			pk:     "wyneuajy",
			pid:    8,
			sid:    15,
		},
		uc{
			dbname: "zzvrkganvh",
			tbname: "bpmmu",
			pk:     "sstdavui",
			pid:    12,
			sid:    15,
		},
		uc{
			dbname: "iowouqzpxc",
			tbname: "adawn",
			pk:     "eqfegfvv",
			pid:    13,
			sid:    30,
		},
		uc{
			dbname: "tcinyvqnzm",
			tbname: "gmvha",
			pk:     "sagzjbhi",
			pid:    11,
			sid:    12,
		},
		uc{
			dbname: "pncmyzlhkx",
			tbname: "xszvb",
			pk:     "wmkgroik",
			pid:    15,
			sid:    16,
		},
		uc{
			dbname: "ndnlvdhgdq",
			tbname: "lnhjc",
			pk:     "rolbvdgw",
			pid:    18,
			sid:    31,
		},
		uc{
			dbname: "mthlkwjniw",
			tbname: "hdeyl",
			pk:     "zugxqhqi",
			pid:    6,
			sid:    31,
		},
		uc{
			dbname: "bllkafhmgg",
			tbname: "phbwz",
			pk:     "rktssrpn",
			pid:    17,
			sid:    26,
		},
		uc{
			dbname: "katamevgjw",
			tbname: "ydndg",
			pk:     "wycelzem",
			pid:    0,
			sid:    17,
		},
		uc{
			dbname: "cujauvpjyr",
			tbname: "bghiu",
			pk:     "pgbnnzsq",
			pid:    9,
			sid:    0,
		},
		uc{
			dbname: "fdxkwkpwhv",
			tbname: "iczhr",
			pk:     "rtynsimk",
			pid:    7,
			sid:    13,
		},
		uc{
			dbname: "hzukiqzsox",
			tbname: "mrfby",
			pk:     "qwnbasln",
			pid:    8,
			sid:    15,
		},
		uc{
			dbname: "gssrbudsms",
			tbname: "hlgki",
			pk:     "uimccaio",
			pid:    32,
			sid:    11,
		},
		uc{
			dbname: "xmvuvxeccv",
			tbname: "ysjvf",
			pk:     "adqnfsta",
			pid:    23,
			sid:    20,
		},
		uc{
			dbname: "zkxongmrlq",
			tbname: "atmbo",
			pk:     "abwgbpgi",
			pid:    14,
			sid:    6,
		},
		uc{
			dbname: "bzbhpjbwua",
			tbname: "khnvc",
			pk:     "idpxwrtc",
			pid:    25,
			sid:    31,
		},
		uc{
			dbname: "orwwpgnaaa",
			tbname: "tuate",
			pk:     "zsaigpfk",
			pid:    2,
			sid:    31,
		},
		uc{
			dbname: "rutgdaqiop",
			tbname: "rhdgq",
			pk:     "xgbagqfw",
			pid:    28,
			sid:    6,
		},
		uc{
			dbname: "emxynepyjv",
			tbname: "fqkki",
			pk:     "kienywnc",
			pid:    26,
			sid:    10,
		},
		uc{
			dbname: "teswtdosky",
			tbname: "ufvjh",
			pk:     "wwkrqkvr",
			pid:    7,
			sid:    14,
		},
		uc{
			dbname: "ugpfbgfrid",
			tbname: "ujvap",
			pk:     "nbegxihe",
			pid:    11,
			sid:    30,
		},
		uc{
			dbname: "ihsxlgqvpw",
			tbname: "pgoou",
			pk:     "wyhfacfs",
			pid:    18,
			sid:    21,
		},
		uc{
			dbname: "pbmbpmrmav",
			tbname: "iusbp",
			pk:     "vjnmbxwl",
			pid:    8,
			sid:    13,
		},
		uc{
			dbname: "xlhdfjarnm",
			tbname: "bfmwz",
			pk:     "okggntmm",
			pid:    31,
			sid:    30,
		},
		uc{
			dbname: "rhkatpeycp",
			tbname: "jvcre",
			pk:     "gyuspazi",
			pid:    4,
			sid:    30,
		},
		uc{
			dbname: "wsmgeojgck",
			tbname: "yfsja",
			pk:     "ccnpcfrz",
			pid:    6,
			sid:    20,
		},
		uc{
			dbname: "vcuiqznmqu",
			tbname: "vqywz",
			pk:     "nqnjckes",
			pid:    21,
			sid:    18,
		},
		uc{
			dbname: "egjyusobxh",
			tbname: "xyfvl",
			pk:     "fbqahpgq",
			pid:    22,
			sid:    20,
		},
		uc{
			dbname: "jhamgrpesy",
			tbname: "doapl",
			pk:     "pygughag",
			pid:    29,
			sid:    3,
		},
		uc{
			dbname: "mrauilviua",
			tbname: "phiyw",
			pk:     "jahinbij",
			pid:    26,
			sid:    20,
		},
		uc{
			dbname: "ttuqnxqlrx",
			tbname: "jgoam",
			pk:     "qqobzzfx",
			pid:    19,
			sid:    15,
		},
		uc{
			dbname: "fiynuutupm",
			tbname: "hbdyv",
			pk:     "dretehlt",
			pid:    14,
			sid:    5,
		},
		uc{
			dbname: "sfivcxesbp",
			tbname: "zetac",
			pk:     "zymwbzwy",
			pid:    16,
			sid:    12,
		},
		uc{
			dbname: "dohzbhbqwv",
			tbname: "vwaft",
			pk:     "dcfgwsam",
			pid:    31,
			sid:    16,
		},
		uc{
			dbname: "yyelisieuh",
			tbname: "wcfpm",
			pk:     "yujpuvmz",
			pid:    13,
			sid:    8,
		},
		uc{
			dbname: "xigphuotha",
			tbname: "evsny",
			pk:     "djgstqki",
			pid:    12,
			sid:    12,
		},
		uc{
			dbname: "zihitkqyse",
			tbname: "xhfnr",
			pk:     "lhcanfdk",
			pid:    32,
			sid:    10,
		},
		uc{
			dbname: "rmzbtdjwxp",
			tbname: "fwuwb",
			pk:     "wdsngywv",
			pid:    29,
			sid:    1,
		},
		uc{
			dbname: "dfjgkpnuqs",
			tbname: "duzmh",
			pk:     "nwseyrly",
			pid:    22,
			sid:    1,
		},
		uc{
			dbname: "qhxxbqnmxx",
			tbname: "ioswl",
			pk:     "kxvmkqak",
			pid:    5,
			sid:    4,
		},
		uc{
			dbname: "larmhdikib",
			tbname: "tpkth",
			pk:     "iivqkcju",
			pid:    16,
			sid:    31,
		},
		uc{
			dbname: "ddguzrcfmv",
			tbname: "gujbi",
			pk:     "aqnmwyce",
			pid:    4,
			sid:    20,
		},
		uc{
			dbname: "kbigumobff",
			tbname: "eaasm",
			pk:     "zsmsmmhk",
			pid:    29,
			sid:    1,
		},
		uc{
			dbname: "clggyixajf",
			tbname: "ggivc",
			pk:     "tpkgaoer",
			pid:    15,
			sid:    15,
		},
		uc{
			dbname: "vwznedmoop",
			tbname: "olyha",
			pk:     "shzjrbeu",
			pid:    22,
			sid:    32,
		},
		uc{
			dbname: "syejboqxao",
			tbname: "mlmuo",
			pk:     "ncfjnutq",
			pid:    8,
			sid:    4,
		},
		uc{
			dbname: "zqaoxpcoqj",
			tbname: "gflhq",
			pk:     "bexqeswa",
			pid:    25,
			sid:    6,
		},
		uc{
			dbname: "qtozzcwhib",
			tbname: "zifdv",
			pk:     "ovhspnln",
			pid:    15,
			sid:    14,
		},
		uc{
			dbname: "idvqbjqtty",
			tbname: "xyfzk",
			pk:     "qdmodkip",
			pid:    17,
			sid:    7,
		},
		uc{
			dbname: "gxnragutgu",
			tbname: "ydezj",
			pk:     "fpfagauu",
			pid:    24,
			sid:    18,
		},
		uc{
			dbname: "gowadtmvlg",
			tbname: "sxkni",
			pk:     "dzojnurh",
			pid:    14,
			sid:    0,
		},
		uc{
			dbname: "ptpcephlka",
			tbname: "tlzxb",
			pk:     "snzpssxr",
			pid:    28,
			sid:    22,
		},
		uc{
			dbname: "ixyhtqwybs",
			tbname: "azhmq",
			pk:     "qbofbyhq",
			pid:    3,
			sid:    30,
		},
		uc{
			dbname: "bpwbvguovw",
			tbname: "xxtmh",
			pk:     "tnpfkwcz",
			pid:    26,
			sid:    0,
		},
		uc{
			dbname: "uizbkxrrcd",
			tbname: "flbvk",
			pk:     "pnpcmfcn",
			pid:    27,
			sid:    16,
		},
		uc{
			dbname: "guvgyapwmi",
			tbname: "eawwt",
			pk:     "zlclkrcv",
			pid:    30,
			sid:    10,
		},
		uc{
			dbname: "umqwhmnlsn",
			tbname: "izuyd",
			pk:     "plcxbcyo",
			pid:    20,
			sid:    6,
		},
		uc{
			dbname: "benwnuicss",
			tbname: "ujaty",
			pk:     "edhuzuzo",
			pid:    10,
			sid:    4,
		},
		uc{
			dbname: "owtzealxvh",
			tbname: "pmdzz",
			pk:     "jzkijqai",
			pid:    3,
			sid:    6,
		},
		uc{
			dbname: "qncbfefoyl",
			tbname: "hbvgm",
			pk:     "wugaylgb",
			pid:    22,
			sid:    31,
		},
		uc{
			dbname: "jhlrsprkaz",
			tbname: "hafxx",
			pk:     "yrbfemel",
			pid:    22,
			sid:    12,
		},
		uc{
			dbname: "eboaddsivr",
			tbname: "ojbou",
			pk:     "txywbrxe",
			pid:    6,
			sid:    12,
		},
		uc{
			dbname: "czuynddpps",
			tbname: "swxdc",
			pk:     "andnotrf",
			pid:    19,
			sid:    15,
		},
		uc{
			dbname: "aixvwehwnc",
			tbname: "mmmhe",
			pk:     "coczhgva",
			pid:    29,
			sid:    20,
		},
		uc{
			dbname: "zoskgqhfpv",
			tbname: "ehzne",
			pk:     "rvrjbxcl",
			pid:    13,
			sid:    21,
		},
		uc{
			dbname: "zhqupdskib",
			tbname: "yjimb",
			pk:     "blbzkjlb",
			pid:    25,
			sid:    28,
		},
		uc{
			dbname: "mzfwreirwh",
			tbname: "azzee",
			pk:     "qicmutrx",
			pid:    20,
			sid:    19,
		},
		uc{
			dbname: "lhnfhsytqv",
			tbname: "qnrgy",
			pk:     "dpyobqwf",
			pid:    11,
			sid:    20,
		},
		uc{
			dbname: "sfeaqnpjvn",
			tbname: "dopvh",
			pk:     "liszohnm",
			pid:    30,
			sid:    31,
		},
		uc{
			dbname: "wrfytlliks",
			tbname: "xhaew",
			pk:     "bqxmifut",
			pid:    23,
			sid:    32,
		},
		uc{
			dbname: "mwakbxkspk",
			tbname: "ipsqk",
			pk:     "fkjxxuvi",
			pid:    28,
			sid:    0,
		},
		uc{
			dbname: "vvzksuqteh",
			tbname: "lvfou",
			pk:     "snjynmnf",
			pid:    0,
			sid:    8,
		},
		uc{
			dbname: "qefyuwgmnt",
			tbname: "neohu",
			pk:     "zbibsiiq",
			pid:    29,
			sid:    2,
		},
		uc{
			dbname: "obshvddyxg",
			tbname: "nqmah",
			pk:     "stuctvpw",
			pid:    3,
			sid:    7,
		},
		uc{
			dbname: "toikjbbygf",
			tbname: "qvhmd",
			pk:     "kyvpibzq",
			pid:    16,
			sid:    11,
		},
		uc{
			dbname: "wkmqvjtega",
			tbname: "prteb",
			pk:     "aqenrwrm",
			pid:    7,
			sid:    16,
		},
		uc{
			dbname: "hbmhxlflyh",
			tbname: "dfkwn",
			pk:     "kgbgtzxy",
			pid:    24,
			sid:    4,
		},
		uc{
			dbname: "yfyknaocgv",
			tbname: "jsmjw",
			pk:     "avmlskkw",
			pid:    4,
			sid:    30,
		},
		uc{
			dbname: "brkugyzyeu",
			tbname: "tckzp",
			pk:     "bfixwnuw",
			pid:    4,
			sid:    25,
		},
		uc{
			dbname: "hhkaxyqvso",
			tbname: "hvbsc",
			pk:     "dscnadkk",
			pid:    32,
			sid:    29,
		},
		uc{
			dbname: "wjfvjzmmzp",
			tbname: "qjvfi",
			pk:     "sryxuedt",
			pid:    2,
			sid:    9,
		},
		uc{
			dbname: "qwmlkwzmed",
			tbname: "amzan",
			pk:     "wpuucheb",
			pid:    18,
			sid:    23,
		},
		uc{
			dbname: "wvggpplvrh",
			tbname: "fhbdn",
			pk:     "bqkbaizo",
			pid:    17,
			sid:    7,
		},
		uc{
			dbname: "ottjwkkkfi",
			tbname: "ccrci",
			pk:     "schbcapk",
			pid:    7,
			sid:    5,
		},
		uc{
			dbname: "rbhhjxrjyd",
			tbname: "jugyk",
			pk:     "xynjwwxe",
			pid:    19,
			sid:    11,
		},
		uc{
			dbname: "ciaiagwhpp",
			tbname: "ozhnz",
			pk:     "auyavqvz",
			pid:    32,
			sid:    22,
		},
		uc{
			dbname: "gurwjioqdd",
			tbname: "girzl",
			pk:     "qzqwisle",
			pid:    24,
			sid:    5,
		},
		uc{
			dbname: "xlyqkqlbde",
			tbname: "niath",
			pk:     "mlqgayko",
			pid:    25,
			sid:    3,
		},
		uc{
			dbname: "jbsqxwmnvq",
			tbname: "govjs",
			pk:     "uphzmmhd",
			pid:    0,
			sid:    10,
		},
		uc{
			dbname: "ngoxnloqos",
			tbname: "vhoqg",
			pk:     "bidhumca",
			pid:    25,
			sid:    22,
		},
		uc{
			dbname: "ptxlacmmjp",
			tbname: "ancvh",
			pk:     "amalikfo",
			pid:    19,
			sid:    12,
		},
		uc{
			dbname: "ctghvokhee",
			tbname: "uhzoa",
			pk:     "tkjgltuo",
			pid:    7,
			sid:    21,
		},
		uc{
			dbname: "sgocbpjehz",
			tbname: "vhxuc",
			pk:     "lzucknpl",
			pid:    10,
			sid:    28,
		},
		uc{
			dbname: "xhrirvsefr",
			tbname: "sfnfu",
			pk:     "cakgwsth",
			pid:    26,
			sid:    22,
		},
		uc{
			dbname: "atwlbvatnl",
			tbname: "yvsuc",
			pk:     "smevlwvo",
			pid:    15,
			sid:    9,
		},
		uc{
			dbname: "owgaqthygm",
			tbname: "xbjlw",
			pk:     "nkzibobh",
			pid:    10,
			sid:    28,
		},
		uc{
			dbname: "paujnxrica",
			tbname: "yyquk",
			pk:     "zypkdtxr",
			pid:    31,
			sid:    19,
		},
		uc{
			dbname: "ubpiaduxud",
			tbname: "zdcgw",
			pk:     "ntpcfeku",
			pid:    16,
			sid:    1,
		},
		uc{
			dbname: "suzdohhdyg",
			tbname: "hcflx",
			pk:     "yeuuhddp",
			pid:    5,
			sid:    15,
		},
		uc{
			dbname: "meqbndvoqq",
			tbname: "myqdx",
			pk:     "nhclkvxq",
			pid:    15,
			sid:    16,
		},
		uc{
			dbname: "hzghaagxuu",
			tbname: "pzmht",
			pk:     "hwigrwfl",
			pid:    7,
			sid:    0,
		},
		uc{
			dbname: "oicbvkewdk",
			tbname: "yrxwo",
			pk:     "dsgqbnas",
			pid:    5,
			sid:    8,
		},
		uc{
			dbname: "imjvucflmf",
			tbname: "ebgui",
			pk:     "xymafpyn",
			pid:    32,
			sid:    17,
		},
		uc{
			dbname: "mtsnuzcmod",
			tbname: "wszik",
			pk:     "cgehsezt",
			pid:    17,
			sid:    1,
		},
		uc{
			dbname: "gwdepcvfqr",
			tbname: "jawjw",
			pk:     "kazqtzjr",
			pid:    8,
			sid:    4,
		},
		uc{
			dbname: "bmuafzbglr",
			tbname: "ihvhx",
			pk:     "ouxixvtx",
			pid:    12,
			sid:    8,
		},
		uc{
			dbname: "gtgxqskcty",
			tbname: "mquxv",
			pk:     "xcwcgbzq",
			pid:    24,
			sid:    13,
		},
		uc{
			dbname: "obfgrzxdyx",
			tbname: "ajtly",
			pk:     "cmcwgaaa",
			pid:    10,
			sid:    27,
		},
		uc{
			dbname: "kajioxnfau",
			tbname: "dccut",
			pk:     "psucxctp",
			pid:    31,
			sid:    32,
		},
		uc{
			dbname: "seecgilgxk",
			tbname: "tdtfb",
			pk:     "zoblwdoy",
			pid:    0,
			sid:    18,
		},
		uc{
			dbname: "vilmfiuxam",
			tbname: "ievti",
			pk:     "ordrwfyn",
			pid:    20,
			sid:    2,
		},
		uc{
			dbname: "vhnfvdorcf",
			tbname: "ndddj",
			pk:     "icwczxav",
			pid:    13,
			sid:    0,
		},
		uc{
			dbname: "tblwtosuqi",
			tbname: "ttvzk",
			pk:     "eiyukccl",
			pid:    8,
			sid:    13,
		},
		uc{
			dbname: "ryqkixabef",
			tbname: "cqfom",
			pk:     "ogsfifsw",
			pid:    10,
			sid:    10,
		},
		uc{
			dbname: "lzfvamvqbg",
			tbname: "wlnsj",
			pk:     "gyeipxbs",
			pid:    0,
			sid:    15,
		},
		uc{
			dbname: "ifvetnysqz",
			tbname: "sikmh",
			pk:     "iruqotcr",
			pid:    30,
			sid:    27,
		},
		uc{
			dbname: "puwyjbnplw",
			tbname: "weqds",
			pk:     "erocucmz",
			pid:    9,
			sid:    15,
		},
		uc{
			dbname: "tpwcerlzlf",
			tbname: "zebvg",
			pk:     "eehsnfee",
			pid:    28,
			sid:    12,
		},
		uc{
			dbname: "ihaiwsuzad",
			tbname: "phhod",
			pk:     "vgztlumk",
			pid:    25,
			sid:    15,
		},
		uc{
			dbname: "ntxseyvsxs",
			tbname: "mqqux",
			pk:     "hguiekbw",
			pid:    21,
			sid:    5,
		},
		uc{
			dbname: "dfdemtdnrf",
			tbname: "lqzuv",
			pk:     "hggmuhbf",
			pid:    25,
			sid:    26,
		},
		uc{
			dbname: "okuefdtscu",
			tbname: "cpecw",
			pk:     "jtaeaiqq",
			pid:    9,
			sid:    32,
		},
		uc{
			dbname: "itdjtmtqtk",
			tbname: "kfocp",
			pk:     "pszfnqmt",
			pid:    17,
			sid:    6,
		},
		uc{
			dbname: "cgxluqauwi",
			tbname: "fufpx",
			pk:     "hykqtekb",
			pid:    31,
			sid:    9,
		},
		uc{
			dbname: "cccmmsuldc",
			tbname: "ymftq",
			pk:     "onqymicn",
			pid:    19,
			sid:    26,
		},
		uc{
			dbname: "atfokafyka",
			tbname: "vzntc",
			pk:     "vowvyjdg",
			pid:    11,
			sid:    11,
		},
		uc{
			dbname: "ypilgzmpop",
			tbname: "mczlp",
			pk:     "ghfikzyl",
			pid:    2,
			sid:    28,
		},
		uc{
			dbname: "nqjnhchuic",
			tbname: "zpenx",
			pk:     "roynnqik",
			pid:    25,
			sid:    18,
		},
		uc{
			dbname: "vaqxsxzgaq",
			tbname: "vnupk",
			pk:     "cubnlwyj",
			pid:    3,
			sid:    27,
		},
		uc{
			dbname: "rbdemvwenp",
			tbname: "moask",
			pk:     "ufnfnnoq",
			pid:    25,
			sid:    2,
		},
		uc{
			dbname: "zojzkexasy",
			tbname: "irfar",
			pk:     "ryinapud",
			pid:    21,
			sid:    23,
		},
		uc{
			dbname: "ekdduffcum",
			tbname: "dlxqi",
			pk:     "dbqnkiaf",
			pid:    31,
			sid:    1,
		},
		uc{
			dbname: "akxmrqtote",
			tbname: "riihx",
			pk:     "syxttajd",
			pid:    32,
			sid:    6,
		},
		uc{
			dbname: "wckqevurwx",
			tbname: "awjko",
			pk:     "iomjzwav",
			pid:    12,
			sid:    19,
		},
		uc{
			dbname: "rgwdbwulgv",
			tbname: "vcavn",
			pk:     "ubxvaonx",
			pid:    27,
			sid:    3,
		},
		uc{
			dbname: "wblmcbdmpb",
			tbname: "wvfem",
			pk:     "vmhcbwjo",
			pid:    12,
			sid:    6,
		},
		uc{
			dbname: "uzjooysdnw",
			tbname: "jrjqp",
			pk:     "gwmhogft",
			pid:    17,
			sid:    21,
		},
		uc{
			dbname: "kojvkyrlog",
			tbname: "pqzmc",
			pk:     "ikpzsuht",
			pid:    22,
			sid:    10,
		},
		uc{
			dbname: "dzhcfmhzud",
			tbname: "wnwsh",
			pk:     "npzoiyxa",
			pid:    21,
			sid:    8,
		},
		uc{
			dbname: "jmalkjljib",
			tbname: "kettn",
			pk:     "hljagera",
			pid:    28,
			sid:    18,
		},
		uc{
			dbname: "bcaubjqwya",
			tbname: "wfaul",
			pk:     "ujxzxnda",
			pid:    32,
			sid:    4,
		},
		uc{
			dbname: "dorhzsnvpr",
			tbname: "jlyul",
			pk:     "keupguxh",
			pid:    2,
			sid:    22,
		},
		uc{
			dbname: "adktydxssk",
			tbname: "phmvz",
			pk:     "pekqyvgp",
			pid:    17,
			sid:    10,
		},
		uc{
			dbname: "wcudeilgjb",
			tbname: "hhaku",
			pk:     "xrqmovni",
			pid:    3,
			sid:    21,
		},
		uc{
			dbname: "asumujsejz",
			tbname: "zsnrb",
			pk:     "kwhqaoft",
			pid:    6,
			sid:    20,
		},
		uc{
			dbname: "wwluyjbgob",
			tbname: "rtxwd",
			pk:     "lcskidjb",
			pid:    29,
			sid:    4,
		},
		uc{
			dbname: "acgcqclahm",
			tbname: "bugje",
			pk:     "dkvnpmta",
			pid:    7,
			sid:    26,
		},
		uc{
			dbname: "wnpzmiswbm",
			tbname: "pldii",
			pk:     "sobdwcmr",
			pid:    10,
			sid:    7,
		},
		uc{
			dbname: "pkaavmbxam",
			tbname: "ojxdf",
			pk:     "ephpiybg",
			pid:    26,
			sid:    11,
		},
		uc{
			dbname: "tpzlsojhtt",
			tbname: "xtsda",
			pk:     "sqxlywot",
			pid:    31,
			sid:    0,
		},
		uc{
			dbname: "jfkgqsidas",
			tbname: "kztdw",
			pk:     "gqdutzdh",
			pid:    31,
			sid:    12,
		},
		uc{
			dbname: "nbzpmlaxml",
			tbname: "imvme",
			pk:     "rpbptqoh",
			pid:    18,
			sid:    7,
		},
		uc{
			dbname: "fepbkwyssy",
			tbname: "ydkdv",
			pk:     "eigxtsqg",
			pid:    23,
			sid:    0,
		},
		uc{
			dbname: "iklubvichs",
			tbname: "osszb",
			pk:     "uqwmyqyp",
			pid:    23,
			sid:    25,
		},
		uc{
			dbname: "mnzxdsicxs",
			tbname: "tsgkx",
			pk:     "cuqkeuft",
			pid:    9,
			sid:    21,
		},
		uc{
			dbname: "dsugyrulai",
			tbname: "xwlrp",
			pk:     "piamnikf",
			pid:    26,
			sid:    3,
		},
		uc{
			dbname: "ovmmxuxrnk",
			tbname: "xfakt",
			pk:     "eywgfznn",
			pid:    21,
			sid:    28,
		},
		uc{
			dbname: "eleikvtolv",
			tbname: "heufb",
			pk:     "xffgetul",
			pid:    0,
			sid:    15,
		},
		uc{
			dbname: "ksvywkxqaa",
			tbname: "rjtff",
			pk:     "yzdxpphp",
			pid:    6,
			sid:    18,
		},
		uc{
			dbname: "tjehhgqwsy",
			tbname: "zfavn",
			pk:     "htuolhdw",
			pid:    9,
			sid:    0,
		},
		uc{
			dbname: "mjhtcloauc",
			tbname: "zmvvr",
			pk:     "jnvfmqus",
			pid:    30,
			sid:    1,
		},
		uc{
			dbname: "inispswdjo",
			tbname: "wbpuo",
			pk:     "edgjnbdl",
			pid:    4,
			sid:    18,
		},
		uc{
			dbname: "jgisczbevc",
			tbname: "gdufn",
			pk:     "kzeuxojh",
			pid:    28,
			sid:    27,
		},
		uc{
			dbname: "ajunieuejn",
			tbname: "tkmoa",
			pk:     "qwukuhjz",
			pid:    8,
			sid:    19,
		},
		uc{
			dbname: "ziykhtffdf",
			tbname: "dnptk",
			pk:     "hcnmthsj",
			pid:    25,
			sid:    28,
		},
		uc{
			dbname: "yfzqplkvib",
			tbname: "ywrjn",
			pk:     "ctshxptn",
			pid:    15,
			sid:    17,
		},
		uc{
			dbname: "qlfddxpztu",
			tbname: "xbjid",
			pk:     "mihlywnk",
			pid:    17,
			sid:    8,
		},
		uc{
			dbname: "pkxanxkvkx",
			tbname: "mrfhr",
			pk:     "jeczsriu",
			pid:    5,
			sid:    5,
		},
		uc{
			dbname: "bdeesccitb",
			tbname: "jkpvp",
			pk:     "uvhvbmuk",
			pid:    26,
			sid:    8,
		},
		uc{
			dbname: "wjwgnfiowx",
			tbname: "nfvhq",
			pk:     "djaqramr",
			pid:    8,
			sid:    11,
		},
		uc{
			dbname: "gsswuubrbf",
			tbname: "aagus",
			pk:     "kvcrbdgs",
			pid:    5,
			sid:    31,
		},
		uc{
			dbname: "iyujscxzyo",
			tbname: "pqdpt",
			pk:     "bkwgwrnc",
			pid:    9,
			sid:    10,
		},
		uc{
			dbname: "ivwwkombcy",
			tbname: "ujlsy",
			pk:     "wjnkvcmo",
			pid:    8,
			sid:    18,
		},
		uc{
			dbname: "ejasykqshv",
			tbname: "bpvcz",
			pk:     "ghsqqjtx",
			pid:    26,
			sid:    9,
		},
		uc{
			dbname: "hcvzpnmlml",
			tbname: "igxwh",
			pk:     "kiihpnfs",
			pid:    21,
			sid:    14,
		},
		uc{
			dbname: "texwlxsutu",
			tbname: "evjsm",
			pk:     "whqfveyt",
			pid:    31,
			sid:    14,
		},
		uc{
			dbname: "gwdpbprrow",
			tbname: "fnrup",
			pk:     "inxxoqap",
			pid:    30,
			sid:    29,
		},
		uc{
			dbname: "yeeuargrkm",
			tbname: "xrcjy",
			pk:     "wqrkcnkq",
			pid:    18,
			sid:    21,
		},
		uc{
			dbname: "axokwqnoci",
			tbname: "gasbg",
			pk:     "igcodgmy",
			pid:    18,
			sid:    6,
		},
		uc{
			dbname: "armrkhjqlk",
			tbname: "jnavm",
			pk:     "yviyacav",
			pid:    6,
			sid:    13,
		},
		uc{
			dbname: "qdmxsswolu",
			tbname: "vlwns",
			pk:     "izeceoof",
			pid:    28,
			sid:    15,
		},
		uc{
			dbname: "yrakvmuveo",
			tbname: "hksdq",
			pk:     "mlsyhtun",
			pid:    27,
			sid:    27,
		},
		uc{
			dbname: "vlizxhuwqb",
			tbname: "aymby",
			pk:     "rjkconmi",
			pid:    16,
			sid:    15,
		},
		uc{
			dbname: "sjmfqiwhnw",
			tbname: "tbymy",
			pk:     "chuwchdu",
			pid:    11,
			sid:    15,
		},
		uc{
			dbname: "ixbwzstadw",
			tbname: "wcmja",
			pk:     "fpgzxnms",
			pid:    11,
			sid:    25,
		},
		uc{
			dbname: "uyurvfindv",
			tbname: "tgycn",
			pk:     "ngqyquiq",
			pid:    3,
			sid:    24,
		},
		uc{
			dbname: "vkagdjboxc",
			tbname: "hcozc",
			pk:     "quxjvpwb",
			pid:    31,
			sid:    12,
		},
		uc{
			dbname: "vdftfpchfp",
			tbname: "wvjam",
			pk:     "eexpuiby",
			pid:    30,
			sid:    30,
		},
		uc{
			dbname: "umesjnsiyr",
			tbname: "vwpod",
			pk:     "kmkiaqpe",
			pid:    16,
			sid:    25,
		},
		uc{
			dbname: "ivgreyxnct",
			tbname: "bmiyr",
			pk:     "dukyxkmi",
			pid:    2,
			sid:    12,
		},
		uc{
			dbname: "zwidohlfwz",
			tbname: "kabep",
			pk:     "ujwnkffb",
			pid:    17,
			sid:    21,
		},
		uc{
			dbname: "ixfktphjng",
			tbname: "ceddm",
			pk:     "mculngrg",
			pid:    3,
			sid:    12,
		},
		uc{
			dbname: "jhmvvkvfvm",
			tbname: "ksbgl",
			pk:     "ynuednrn",
			pid:    1,
			sid:    13,
		},
		uc{
			dbname: "srgkcfafxe",
			tbname: "ybdgz",
			pk:     "bulohiva",
			pid:    13,
			sid:    31,
		},
		uc{
			dbname: "ybigzpxxtz",
			tbname: "opttk",
			pk:     "lffhotgt",
			pid:    11,
			sid:    8,
		},
		uc{
			dbname: "weywkgapwy",
			tbname: "hwmvf",
			pk:     "vbicoqlo",
			pid:    20,
			sid:    0,
		},
		uc{
			dbname: "tlpyeofqpt",
			tbname: "qkzrt",
			pk:     "waqjjnkh",
			pid:    7,
			sid:    29,
		},
		uc{
			dbname: "latrsbecab",
			tbname: "loowh",
			pk:     "oncchsxa",
			pid:    8,
			sid:    22,
		},
		uc{
			dbname: "mtelolszay",
			tbname: "czbyn",
			pk:     "lhxtzsoe",
			pid:    17,
			sid:    15,
		},
		uc{
			dbname: "fvugakegvo",
			tbname: "jwols",
			pk:     "povsvjqk",
			pid:    23,
			sid:    11,
		},
		uc{
			dbname: "exvmntjdpf",
			tbname: "ydmme",
			pk:     "lttmzlms",
			pid:    4,
			sid:    25,
		},
		uc{
			dbname: "oigniuxcsf",
			tbname: "bjnrc",
			pk:     "dicbrbrz",
			pid:    23,
			sid:    15,
		},
		uc{
			dbname: "tzhgfruuut",
			tbname: "rmsvq",
			pk:     "kgqrrqpc",
			pid:    1,
			sid:    6,
		},
		uc{
			dbname: "finbnitjdm",
			tbname: "fkyqb",
			pk:     "hfwgehwf",
			pid:    24,
			sid:    21,
		},
		uc{
			dbname: "jrluzumxnl",
			tbname: "cpwnl",
			pk:     "zrtiojle",
			pid:    5,
			sid:    3,
		},
		uc{
			dbname: "uassvvaduz",
			tbname: "wvidh",
			pk:     "qabxxcva",
			pid:    18,
			sid:    2,
		},
		uc{
			dbname: "ldvxvsujrs",
			tbname: "evlbt",
			pk:     "jlshnrpm",
			pid:    5,
			sid:    2,
		},
		uc{
			dbname: "kroftpulta",
			tbname: "xsslu",
			pk:     "koahjnue",
			pid:    22,
			sid:    22,
		},
		uc{
			dbname: "qewkvgqwhs",
			tbname: "ocggw",
			pk:     "gkzmppxb",
			pid:    29,
			sid:    26,
		},
		uc{
			dbname: "clrdsvsxai",
			tbname: "kyqhv",
			pk:     "xfwyxipy",
			pid:    15,
			sid:    16,
		},
		uc{
			dbname: "bkmwnmrkmb",
			tbname: "zcrnu",
			pk:     "jsjvsmif",
			pid:    10,
			sid:    26,
		},
		uc{
			dbname: "xzqxzgyeuu",
			tbname: "jwfpv",
			pk:     "zutwadqf",
			pid:    8,
			sid:    6,
		},
		uc{
			dbname: "qdpuyhzjit",
			tbname: "mezww",
			pk:     "doptyzej",
			pid:    5,
			sid:    14,
		},
		uc{
			dbname: "ahuaxuwqks",
			tbname: "iijqz",
			pk:     "kugsbsak",
			pid:    30,
			sid:    19,
		},
		uc{
			dbname: "hhdsaxwdwo",
			tbname: "nswdk",
			pk:     "jilnqccf",
			pid:    16,
			sid:    26,
		},
		uc{
			dbname: "zjomivuakt",
			tbname: "gvlwm",
			pk:     "jxdreeho",
			pid:    32,
			sid:    24,
		},
		uc{
			dbname: "rqctqztoly",
			tbname: "mpauh",
			pk:     "ikzlgoju",
			pid:    8,
			sid:    9,
		},
		uc{
			dbname: "ustzmevcpw",
			tbname: "zhyrd",
			pk:     "maqypzsq",
			pid:    3,
			sid:    15,
		},
		uc{
			dbname: "nbqgbqmsij",
			tbname: "xfugp",
			pk:     "cijnqekm",
			pid:    21,
			sid:    32,
		},
		uc{
			dbname: "weumebfnwg",
			tbname: "wvofl",
			pk:     "szgrwabi",
			pid:    14,
			sid:    7,
		},
		uc{
			dbname: "brewbegbuv",
			tbname: "heksw",
			pk:     "ehxuskni",
			pid:    1,
			sid:    29,
		},
		uc{
			dbname: "ldyynawwzj",
			tbname: "ntnyu",
			pk:     "bxzkvblq",
			pid:    28,
			sid:    10,
		},
		uc{
			dbname: "cjfmxdwige",
			tbname: "pentz",
			pk:     "ydvyhjhm",
			pid:    6,
			sid:    12,
		},
		uc{
			dbname: "zwnyyrxhnv",
			tbname: "iaqwr",
			pk:     "thumanfy",
			pid:    11,
			sid:    17,
		},
		uc{
			dbname: "zydowcugkp",
			tbname: "corhc",
			pk:     "mafhhoem",
			pid:    21,
			sid:    5,
		},
		uc{
			dbname: "umttqozths",
			tbname: "qmaii",
			pk:     "ecqpivgw",
			pid:    4,
			sid:    21,
		},
		uc{
			dbname: "nsesezlkos",
			tbname: "eiraz",
			pk:     "cttfwcjj",
			pid:    14,
			sid:    4,
		},
		uc{
			dbname: "ogwbyuwbtk",
			tbname: "goxts",
			pk:     "rspifsbf",
			pid:    3,
			sid:    17,
		},
		uc{
			dbname: "kgmzivytim",
			tbname: "ffpmu",
			pk:     "dhpjfqee",
			pid:    20,
			sid:    26,
		},
		uc{
			dbname: "afplawnsqx",
			tbname: "sluby",
			pk:     "xmkwyyrz",
			pid:    14,
			sid:    4,
		},
		uc{
			dbname: "jpqqkjwljo",
			tbname: "vytwf",
			pk:     "blsujsgo",
			pid:    6,
			sid:    12,
		},
		uc{
			dbname: "vhqhuosekg",
			tbname: "zhdsv",
			pk:     "iswbtjbt",
			pid:    20,
			sid:    13,
		},
		uc{
			dbname: "ntqxcftlig",
			tbname: "wdxbq",
			pk:     "qmnazybp",
			pid:    20,
			sid:    9,
		},
		uc{
			dbname: "aezhnynrby",
			tbname: "pjewd",
			pk:     "wngouqiu",
			pid:    11,
			sid:    18,
		},
		uc{
			dbname: "jtwlrmslqm",
			tbname: "hnsxu",
			pk:     "ctnrdzij",
			pid:    2,
			sid:    19,
		},
		uc{
			dbname: "bkrtqrzbeb",
			tbname: "tplmv",
			pk:     "yhxklstd",
			pid:    0,
			sid:    16,
		},
		uc{
			dbname: "nqicwbszpj",
			tbname: "yyjfk",
			pk:     "wluyicgr",
			pid:    4,
			sid:    9,
		},
		uc{
			dbname: "xmjleooggb",
			tbname: "ddafb",
			pk:     "izdaqtlj",
			pid:    12,
			sid:    15,
		},
		uc{
			dbname: "iapydyhlct",
			tbname: "moxpq",
			pk:     "ggcjiejd",
			pid:    9,
			sid:    23,
		},
		uc{
			dbname: "asjgvpgukr",
			tbname: "syhlf",
			pk:     "kruqdybo",
			pid:    14,
			sid:    9,
		},
		uc{
			dbname: "igydmkwttx",
			tbname: "jipgj",
			pk:     "wvdcnkec",
			pid:    17,
			sid:    12,
		},
		uc{
			dbname: "bmflsyoafq",
			tbname: "nmohx",
			pk:     "sevlrlfx",
			pid:    15,
			sid:    11,
		},
		uc{
			dbname: "ayafrvpilt",
			tbname: "ecdpl",
			pk:     "ifktvcfp",
			pid:    18,
			sid:    23,
		},
		uc{
			dbname: "pjzmgopyah",
			tbname: "fcxtx",
			pk:     "bblvnakm",
			pid:    28,
			sid:    12,
		},
		uc{
			dbname: "uleuxhxrpc",
			tbname: "qpsec",
			pk:     "artmwkeb",
			pid:    32,
			sid:    27,
		},
		uc{
			dbname: "ttlohogeij",
			tbname: "wvhga",
			pk:     "tzwidcta",
			pid:    32,
			sid:    7,
		},
		uc{
			dbname: "syzwbhmvhm",
			tbname: "qubpy",
			pk:     "lsahymxa",
			pid:    15,
			sid:    25,
		},
		uc{
			dbname: "bddoigljcm",
			tbname: "ztgfl",
			pk:     "yvwsfoqr",
			pid:    28,
			sid:    29,
		},
		uc{
			dbname: "bhvgjlunju",
			tbname: "uzetn",
			pk:     "bydqihhj",
			pid:    20,
			sid:    25,
		},
		uc{
			dbname: "eawkunrzmp",
			tbname: "nfpfo",
			pk:     "rlxjgjdd",
			pid:    13,
			sid:    32,
		},
		uc{
			dbname: "rtizgvhlrh",
			tbname: "ttpzz",
			pk:     "nlsdupmk",
			pid:    8,
			sid:    2,
		},
		uc{
			dbname: "egdwiaocfy",
			tbname: "conxk",
			pk:     "pdeewoqz",
			pid:    8,
			sid:    21,
		},
		uc{
			dbname: "twwesaaabn",
			tbname: "hyxoz",
			pk:     "wwtylcip",
			pid:    7,
			sid:    20,
		},
		uc{
			dbname: "jfdsmwgpgb",
			tbname: "cxkil",
			pk:     "hvnntuir",
			pid:    24,
			sid:    3,
		},
		uc{
			dbname: "nsrxofffde",
			tbname: "arxkk",
			pk:     "lvvpqsrh",
			pid:    14,
			sid:    28,
		},
		uc{
			dbname: "mkwjpvymth",
			tbname: "whlur",
			pk:     "jeawkhhc",
			pid:    14,
			sid:    21,
		},
		uc{
			dbname: "hqbejgznnp",
			tbname: "uodbl",
			pk:     "eqebeugs",
			pid:    20,
			sid:    23,
		},
		uc{
			dbname: "mxcodnkbsx",
			tbname: "rhrty",
			pk:     "yycrkxtq",
			pid:    25,
			sid:    19,
		},
		uc{
			dbname: "azlmoaysvh",
			tbname: "avwzy",
			pk:     "zemcaiqc",
			pid:    30,
			sid:    2,
		},
		uc{
			dbname: "bfyuhnyjbe",
			tbname: "ftfuj",
			pk:     "ftjpqbvd",
			pid:    26,
			sid:    31,
		},
		uc{
			dbname: "bqmnapelsz",
			tbname: "kmqqt",
			pk:     "ttrwqyza",
			pid:    25,
			sid:    32,
		},
		uc{
			dbname: "kinyymsmsj",
			tbname: "rmkys",
			pk:     "vjcyasdw",
			pid:    18,
			sid:    22,
		},
		uc{
			dbname: "oolsfiiydo",
			tbname: "fkdnd",
			pk:     "oojbouxi",
			pid:    18,
			sid:    27,
		},
		uc{
			dbname: "pbpoglxbwv",
			tbname: "ppoqt",
			pk:     "hcsgsjns",
			pid:    21,
			sid:    32,
		},
		uc{
			dbname: "uabqfgtqmx",
			tbname: "hheyn",
			pk:     "tudtautj",
			pid:    7,
			sid:    27,
		},
		uc{
			dbname: "royiaggquo",
			tbname: "osykn",
			pk:     "maubtkcy",
			pid:    18,
			sid:    4,
		},
		uc{
			dbname: "bghaycsnvt",
			tbname: "vslfi",
			pk:     "pfgbdqyf",
			pid:    20,
			sid:    15,
		},
		uc{
			dbname: "ocdruailaa",
			tbname: "dtdpy",
			pk:     "giedpodi",
			pid:    5,
			sid:    29,
		},
		uc{
			dbname: "ypavtkgcts",
			tbname: "oqrfz",
			pk:     "njpeyswt",
			pid:    20,
			sid:    20,
		},
		uc{
			dbname: "yxalljclcx",
			tbname: "uijif",
			pk:     "qzlbosbk",
			pid:    32,
			sid:    32,
		},
		uc{
			dbname: "arvvmqgacv",
			tbname: "kgslr",
			pk:     "qxvozmck",
			pid:    24,
			sid:    24,
		},
		uc{
			dbname: "vlvdwxgbqs",
			tbname: "fbmfk",
			pk:     "gynmqyio",
			pid:    5,
			sid:    22,
		},
		uc{
			dbname: "irmqbgcjhy",
			tbname: "dhzap",
			pk:     "zcbchsfu",
			pid:    15,
			sid:    28,
		},
		uc{
			dbname: "koiyvkziss",
			tbname: "dtmoj",
			pk:     "bewhvltr",
			pid:    24,
			sid:    9,
		},
		uc{
			dbname: "cjvvyyisix",
			tbname: "vokzg",
			pk:     "jtibvbwy",
			pid:    21,
			sid:    18,
		},
		uc{
			dbname: "hnfehnsqid",
			tbname: "xuwmo",
			pk:     "zkvvvawe",
			pid:    6,
			sid:    11,
		},
		uc{
			dbname: "zxvkzkbtpf",
			tbname: "xhjce",
			pk:     "qjbqfedp",
			pid:    15,
			sid:    13,
		},
		uc{
			dbname: "vbmcaegjlz",
			tbname: "dzmrj",
			pk:     "qohxdxac",
			pid:    31,
			sid:    32,
		},
		uc{
			dbname: "uggxjsgbau",
			tbname: "ldswq",
			pk:     "rceylwfj",
			pid:    5,
			sid:    29,
		},
		uc{
			dbname: "lbgspabvio",
			tbname: "edfzt",
			pk:     "tawgsaer",
			pid:    20,
			sid:    20,
		},
		uc{
			dbname: "cdpplwpnom",
			tbname: "teewm",
			pk:     "ypcqvaco",
			pid:    12,
			sid:    3,
		},
		uc{
			dbname: "qolvfgblgc",
			tbname: "bigst",
			pk:     "qoiqmxms",
			pid:    17,
			sid:    6,
		},
		uc{
			dbname: "xgmvwyjgav",
			tbname: "pqpkw",
			pk:     "wykinggz",
			pid:    26,
			sid:    14,
		},
		uc{
			dbname: "aacajzmeas",
			tbname: "nfqwn",
			pk:     "jspkckpw",
			pid:    12,
			sid:    21,
		},
		uc{
			dbname: "kjttjsaomj",
			tbname: "ntjru",
			pk:     "yfparlzx",
			pid:    17,
			sid:    24,
		},
		uc{
			dbname: "dzkxemihjj",
			tbname: "pdbfp",
			pk:     "binjfrhr",
			pid:    18,
			sid:    27,
		},
		uc{
			dbname: "kvgmfenttq",
			tbname: "rescp",
			pk:     "pfviaabt",
			pid:    14,
			sid:    11,
		},
		uc{
			dbname: "avuzmhvali",
			tbname: "svify",
			pk:     "nndmulde",
			pid:    19,
			sid:    13,
		},
		uc{
			dbname: "lpupwceitk",
			tbname: "dbyml",
			pk:     "dwlmyeuv",
			pid:    10,
			sid:    32,
		},
		uc{
			dbname: "gmvfkhtqkx",
			tbname: "yvwfb",
			pk:     "vmdsiian",
			pid:    17,
			sid:    22,
		},
		uc{
			dbname: "yojvpeaaju",
			tbname: "gzlwu",
			pk:     "ulskhcsu",
			pid:    24,
			sid:    7,
		},
		uc{
			dbname: "vnlzaqmivb",
			tbname: "piaiz",
			pk:     "btwxjlli",
			pid:    14,
			sid:    4,
		},
		uc{
			dbname: "ljbltmgxgy",
			tbname: "tzrst",
			pk:     "jmcljhvl",
			pid:    3,
			sid:    28,
		},
		uc{
			dbname: "morykzldny",
			tbname: "lhdhm",
			pk:     "uqihsxri",
			pid:    14,
			sid:    1,
		},
		uc{
			dbname: "xzixogyndl",
			tbname: "csnsg",
			pk:     "yqlfrlmu",
			pid:    5,
			sid:    21,
		},
		uc{
			dbname: "viuvrfdroh",
			tbname: "qpwtp",
			pk:     "vpyiujbv",
			pid:    9,
			sid:    5,
		},
		uc{
			dbname: "cbwtegojsj",
			tbname: "nmejh",
			pk:     "lgtkqjcf",
			pid:    25,
			sid:    29,
		},
		uc{
			dbname: "pqbcjxvonk",
			tbname: "ckehq",
			pk:     "ltrvbkuw",
			pid:    31,
			sid:    25,
		},
		uc{
			dbname: "qbnsmkkshd",
			tbname: "hwnoq",
			pk:     "hhijykma",
			pid:    11,
			sid:    29,
		},
		uc{
			dbname: "augqwhauxq",
			tbname: "nlsaa",
			pk:     "cbegdnmh",
			pid:    31,
			sid:    8,
		},
		uc{
			dbname: "llansykorp",
			tbname: "xzipy",
			pk:     "zbzbhpqh",
			pid:    24,
			sid:    32,
		},
		uc{
			dbname: "kytwudzypu",
			tbname: "stsht",
			pk:     "wmwxoudd",
			pid:    23,
			sid:    7,
		},
		uc{
			dbname: "tzzzxxeusb",
			tbname: "tekyh",
			pk:     "toallvqw",
			pid:    3,
			sid:    18,
		},
		uc{
			dbname: "yyinfekxxe",
			tbname: "jlkcy",
			pk:     "taifkgqr",
			pid:    10,
			sid:    25,
		},
		uc{
			dbname: "ygqweguiwq",
			tbname: "dytkn",
			pk:     "oawqmbec",
			pid:    19,
			sid:    9,
		},
		uc{
			dbname: "qisldypxpx",
			tbname: "tmllv",
			pk:     "jlxcegfp",
			pid:    22,
			sid:    15,
		},
		uc{
			dbname: "weklcuydon",
			tbname: "qspkv",
			pk:     "owddktml",
			pid:    30,
			sid:    23,
		},
		uc{
			dbname: "jelylhwakz",
			tbname: "zyorj",
			pk:     "thknuitg",
			pid:    30,
			sid:    18,
		},
		uc{
			dbname: "dukjjwqiau",
			tbname: "rcxjh",
			pk:     "mkcyxpkw",
			pid:    7,
			sid:    3,
		},
		uc{
			dbname: "sypcddorie",
			tbname: "iryzr",
			pk:     "lbuyehwr",
			pid:    10,
			sid:    27,
		},
		uc{
			dbname: "wyqcjesqgk",
			tbname: "yvnou",
			pk:     "ldbxetwt",
			pid:    0,
			sid:    13,
		},
		uc{
			dbname: "wevcgpvqea",
			tbname: "susub",
			pk:     "vqijnpsw",
			pid:    28,
			sid:    31,
		},
		uc{
			dbname: "xbescooiis",
			tbname: "kxbua",
			pk:     "rfewymgd",
			pid:    5,
			sid:    27,
		},
		uc{
			dbname: "whuhqoncdn",
			tbname: "ygfls",
			pk:     "rkxwweus",
			pid:    24,
			sid:    13,
		},
		uc{
			dbname: "sheeyfhxqt",
			tbname: "fuhba",
			pk:     "haqimybt",
			pid:    15,
			sid:    22,
		},
		uc{
			dbname: "xawuyxfisb",
			tbname: "lvuqn",
			pk:     "axgkvple",
			pid:    10,
			sid:    21,
		},
		uc{
			dbname: "frjckjpxig",
			tbname: "ljpit",
			pk:     "mqtunkks",
			pid:    5,
			sid:    3,
		},
		uc{
			dbname: "xxlgadreay",
			tbname: "rpmpv",
			pk:     "ixpmsgix",
			pid:    1,
			sid:    6,
		},
		uc{
			dbname: "txciplqaba",
			tbname: "jxpyx",
			pk:     "aplafzrc",
			pid:    27,
			sid:    0,
		},
		uc{
			dbname: "onurqdykqv",
			tbname: "iyjdl",
			pk:     "piohxxgk",
			pid:    11,
			sid:    4,
		},
		uc{
			dbname: "ciyvbqujqt",
			tbname: "axnvr",
			pk:     "xstmhwnu",
			pid:    17,
			sid:    9,
		},
		uc{
			dbname: "xicgjoybkl",
			tbname: "puqtr",
			pk:     "lnnzbhbt",
			pid:    2,
			sid:    24,
		},
		uc{
			dbname: "gnsfkvlttv",
			tbname: "bohaf",
			pk:     "gwzgjxro",
			pid:    11,
			sid:    24,
		},
		uc{
			dbname: "ungheiyojd",
			tbname: "touaj",
			pk:     "jvsklktu",
			pid:    14,
			sid:    2,
		},
		uc{
			dbname: "hdvsxuzomd",
			tbname: "bfgfo",
			pk:     "shotdiey",
			pid:    30,
			sid:    22,
		},
		uc{
			dbname: "recqsovwqm",
			tbname: "onqnx",
			pk:     "pzxubpdp",
			pid:    16,
			sid:    30,
		},
		uc{
			dbname: "jjjzckiwaz",
			tbname: "aawgl",
			pk:     "kdealcrc",
			pid:    0,
			sid:    8,
		},
		uc{
			dbname: "ayhistnkno",
			tbname: "yvekz",
			pk:     "fohkvzae",
			pid:    16,
			sid:    32,
		},
		uc{
			dbname: "gadrwuflic",
			tbname: "fcozo",
			pk:     "yhgotndx",
			pid:    15,
			sid:    2,
		},
		uc{
			dbname: "yiwuexdxjr",
			tbname: "xpupe",
			pk:     "scwumjdy",
			pid:    29,
			sid:    5,
		},
		uc{
			dbname: "lespnrwnsw",
			tbname: "ynpch",
			pk:     "ogyanhkh",
			pid:    10,
			sid:    8,
		},
		uc{
			dbname: "tmvjsdgbcx",
			tbname: "fybpr",
			pk:     "mexciufl",
			pid:    19,
			sid:    11,
		},
		uc{
			dbname: "igieslmvzh",
			tbname: "fruao",
			pk:     "sxrhzthw",
			pid:    1,
			sid:    24,
		},
		uc{
			dbname: "lmkcgxopan",
			tbname: "hzyaa",
			pk:     "gvcyywoh",
			pid:    26,
			sid:    22,
		},
		uc{
			dbname: "dhnhtlbnra",
			tbname: "jbmzf",
			pk:     "ykmiozbp",
			pid:    0,
			sid:    0,
		},
		uc{
			dbname: "xteffpgnyd",
			tbname: "tkuey",
			pk:     "bkcwcfot",
			pid:    8,
			sid:    15,
		},
		uc{
			dbname: "buvzicdsep",
			tbname: "squoe",
			pk:     "fjqaqzpe",
			pid:    24,
			sid:    13,
		},
		uc{
			dbname: "zcdlgujozz",
			tbname: "xyyvu",
			pk:     "bdiqjxyb",
			pid:    4,
			sid:    0,
		},
		uc{
			dbname: "ogekcporff",
			tbname: "lnzwv",
			pk:     "tppcobku",
			pid:    29,
			sid:    10,
		},
		uc{
			dbname: "favalnnjms",
			tbname: "uikcw",
			pk:     "tajbwjdp",
			pid:    12,
			sid:    9,
		},
		uc{
			dbname: "ukitmjwehr",
			tbname: "drnut",
			pk:     "hmessmit",
			pid:    24,
			sid:    20,
		},
		uc{
			dbname: "xifyufajpk",
			tbname: "bilbn",
			pk:     "ibgtiogq",
			pid:    30,
			sid:    26,
		},
		uc{
			dbname: "mzmmmxowvb",
			tbname: "wsrwt",
			pk:     "vdiqbdpo",
			pid:    1,
			sid:    5,
		},
		uc{
			dbname: "bakffhqadf",
			tbname: "zckry",
			pk:     "modkbjeo",
			pid:    4,
			sid:    5,
		},
		uc{
			dbname: "yeuxjxagwx",
			tbname: "zlrjk",
			pk:     "aeudnugp",
			pid:    28,
			sid:    15,
		},
		uc{
			dbname: "msvupfquvp",
			tbname: "pbqkj",
			pk:     "ofzdwrkx",
			pid:    2,
			sid:    7,
		},
		uc{
			dbname: "yodbqxywqz",
			tbname: "xolso",
			pk:     "watlltms",
			pid:    8,
			sid:    23,
		},
		uc{
			dbname: "etkolwmwwq",
			tbname: "isfgx",
			pk:     "ugylnbru",
			pid:    25,
			sid:    30,
		},
		uc{
			dbname: "ucfblghlce",
			tbname: "mogwy",
			pk:     "ohdpyirj",
			pid:    5,
			sid:    12,
		},
		uc{
			dbname: "fdruogppdr",
			tbname: "mmcoz",
			pk:     "wylutyam",
			pid:    19,
			sid:    12,
		},
		uc{
			dbname: "etzddgjfbp",
			tbname: "jqare",
			pk:     "phwpgmzi",
			pid:    28,
			sid:    2,
		},
		uc{
			dbname: "rpwrjveddf",
			tbname: "eyasa",
			pk:     "butcvotu",
			pid:    4,
			sid:    30,
		},
		uc{
			dbname: "yirhvrnacj",
			tbname: "niofu",
			pk:     "xaloafuf",
			pid:    23,
			sid:    4,
		},
		uc{
			dbname: "vklmoicick",
			tbname: "xbplf",
			pk:     "ekavgziy",
			pid:    7,
			sid:    8,
		},
		uc{
			dbname: "kbxqayjdpt",
			tbname: "uhddk",
			pk:     "oppweogl",
			pid:    17,
			sid:    27,
		},
		uc{
			dbname: "poggjmblsp",
			tbname: "nsunw",
			pk:     "exchfvzy",
			pid:    29,
			sid:    11,
		},
		uc{
			dbname: "ljlyjfbeso",
			tbname: "mawnx",
			pk:     "qrtbjrpm",
			pid:    15,
			sid:    2,
		},
		uc{
			dbname: "sbixlnqdgj",
			tbname: "suibm",
			pk:     "hhruyxxm",
			pid:    28,
			sid:    26,
		},
		uc{
			dbname: "blpdntmjfx",
			tbname: "qrpur",
			pk:     "bizqvwih",
			pid:    23,
			sid:    19,
		},
		uc{
			dbname: "mymuyyxciy",
			tbname: "xmlps",
			pk:     "oumyjcoe",
			pid:    7,
			sid:    12,
		},
		uc{
			dbname: "ufsfzvakim",
			tbname: "nufii",
			pk:     "xtdbtpny",
			pid:    18,
			sid:    24,
		},
		uc{
			dbname: "blggkyueyn",
			tbname: "agdgo",
			pk:     "ldshpbkb",
			pid:    32,
			sid:    21,
		},
		uc{
			dbname: "driicmqaze",
			tbname: "kuxbb",
			pk:     "tcvvblxu",
			pid:    22,
			sid:    19,
		},
		uc{
			dbname: "kngxqpxzzt",
			tbname: "wxtly",
			pk:     "kcrmqmpc",
			pid:    13,
			sid:    14,
		},
		uc{
			dbname: "rcjelkdsaz",
			tbname: "lxsie",
			pk:     "bduahidw",
			pid:    25,
			sid:    14,
		},
		uc{
			dbname: "zrurjfbpwg",
			tbname: "amogn",
			pk:     "isgfwhqj",
			pid:    21,
			sid:    32,
		},
		uc{
			dbname: "jsyeotyjdb",
			tbname: "gntev",
			pk:     "qitbwfdm",
			pid:    27,
			sid:    24,
		},
		uc{
			dbname: "rtouwtyjtk",
			tbname: "odyoo",
			pk:     "lhulxewl",
			pid:    12,
			sid:    21,
		},
		uc{
			dbname: "znvawjtjuu",
			tbname: "hrbpc",
			pk:     "wccescfr",
			pid:    23,
			sid:    11,
		},
		uc{
			dbname: "kqiglwefqd",
			tbname: "lgmlb",
			pk:     "mhkadroz",
			pid:    3,
			sid:    31,
		},
		uc{
			dbname: "yjovofabqo",
			tbname: "lnlnx",
			pk:     "xiklvkmx",
			pid:    13,
			sid:    9,
		},
		uc{
			dbname: "pgcnykvisa",
			tbname: "ywuct",
			pk:     "qgtrchoh",
			pid:    19,
			sid:    21,
		},
		uc{
			dbname: "ifhunyqdiq",
			tbname: "jvbyy",
			pk:     "jfnqzsjr",
			pid:    32,
			sid:    25,
		},
		uc{
			dbname: "mrgfncfsid",
			tbname: "fpmrc",
			pk:     "xqlytbfa",
			pid:    9,
			sid:    25,
		},
		uc{
			dbname: "shyrmkbntp",
			tbname: "ulmuq",
			pk:     "zgunnhic",
			pid:    3,
			sid:    17,
		},
		uc{
			dbname: "dwyzrkxagp",
			tbname: "ttvhe",
			pk:     "rozlkmre",
			pid:    1,
			sid:    21,
		},
		uc{
			dbname: "xtjzcyntdn",
			tbname: "iarur",
			pk:     "ehpknhlt",
			pid:    31,
			sid:    0,
		},
		uc{
			dbname: "nvdbyigltr",
			tbname: "qfpbh",
			pk:     "ymhrybtv",
			pid:    0,
			sid:    32,
		},
		uc{
			dbname: "washjsyuqs",
			tbname: "kbaql",
			pk:     "xwgccdha",
			pid:    29,
			sid:    11,
		},
		uc{
			dbname: "qmtndlkmkg",
			tbname: "hxsde",
			pk:     "zfdrldio",
			pid:    16,
			sid:    29,
		},
		uc{
			dbname: "ngosmlzuey",
			tbname: "fzkzr",
			pk:     "dmehfsja",
			pid:    17,
			sid:    15,
		},
		uc{
			dbname: "altkcnbfcj",
			tbname: "prynn",
			pk:     "ncbbwlwo",
			pid:    18,
			sid:    29,
		},
		uc{
			dbname: "rttwpzashn",
			tbname: "ytnre",
			pk:     "yxhuxmed",
			pid:    7,
			sid:    18,
		},
		uc{
			dbname: "ykrmjbcjdi",
			tbname: "rrthb",
			pk:     "enkktbni",
			pid:    26,
			sid:    9,
		},
		uc{
			dbname: "lutcapuyjk",
			tbname: "pzqsv",
			pk:     "tlypyjsx",
			pid:    4,
			sid:    6,
		},
		uc{
			dbname: "citfixbbko",
			tbname: "bpfny",
			pk:     "fwcqguzi",
			pid:    5,
			sid:    24,
		},
		uc{
			dbname: "rgtbpgqgbs",
			tbname: "mspqm",
			pk:     "tbstsfxf",
			pid:    27,
			sid:    1,
		},
		uc{
			dbname: "fmleuirtqo",
			tbname: "listg",
			pk:     "agmyxvvd",
			pid:    32,
			sid:    16,
		},
		uc{
			dbname: "nzqxtbowab",
			tbname: "bzamv",
			pk:     "sotvzmqk",
			pid:    5,
			sid:    7,
		},
		uc{
			dbname: "bklqmoknel",
			tbname: "tyjro",
			pk:     "pzfenjqr",
			pid:    0,
			sid:    26,
		},
		uc{
			dbname: "rhfilmorcg",
			tbname: "eikij",
			pk:     "pkkupryn",
			pid:    7,
			sid:    1,
		},
		uc{
			dbname: "fiifqatugd",
			tbname: "lqcve",
			pk:     "yftcrkkc",
			pid:    14,
			sid:    20,
		},
		uc{
			dbname: "jztuarknde",
			tbname: "loilw",
			pk:     "drspckwq",
			pid:    22,
			sid:    30,
		},
		uc{
			dbname: "zshkisjaht",
			tbname: "kalvy",
			pk:     "jjoluhsi",
			pid:    19,
			sid:    32,
		},
		uc{
			dbname: "mpqatitocv",
			tbname: "eleqm",
			pk:     "myjjxcky",
			pid:    21,
			sid:    15,
		},
		uc{
			dbname: "elqskcnvve",
			tbname: "rwcag",
			pk:     "mbstpnmb",
			pid:    10,
			sid:    13,
		},
		uc{
			dbname: "srmecqcgik",
			tbname: "jmeru",
			pk:     "bwatwhos",
			pid:    11,
			sid:    13,
		},
		uc{
			dbname: "cnzgorwpsr",
			tbname: "qsevl",
			pk:     "xjwtkygf",
			pid:    2,
			sid:    31,
		},
		uc{
			dbname: "jykrvihonq",
			tbname: "aluqn",
			pk:     "hvojsdtq",
			pid:    10,
			sid:    2,
		},
		uc{
			dbname: "mcaosvognf",
			tbname: "nhxco",
			pk:     "vgeaxvwq",
			pid:    13,
			sid:    16,
		},
		uc{
			dbname: "rqivypagml",
			tbname: "hgwxr",
			pk:     "eimdntnx",
			pid:    2,
			sid:    10,
		},
		uc{
			dbname: "lkqrpuyndx",
			tbname: "izoiv",
			pk:     "imtfwfzz",
			pid:    7,
			sid:    5,
		},
		uc{
			dbname: "szuhzpicis",
			tbname: "vwwyu",
			pk:     "zxrnbbsj",
			pid:    0,
			sid:    19,
		},
		uc{
			dbname: "ykyxlterzm",
			tbname: "irdjw",
			pk:     "bhqowgjl",
			pid:    20,
			sid:    2,
		},
		uc{
			dbname: "slbhkacxyk",
			tbname: "akzik",
			pk:     "dlcdyosy",
			pid:    12,
			sid:    22,
		},
		uc{
			dbname: "azwgdbietz",
			tbname: "tlplg",
			pk:     "athkfsqj",
			pid:    32,
			sid:    18,
		},
		uc{
			dbname: "stxvkxzbjh",
			tbname: "eswyk",
			pk:     "chgixyfm",
			pid:    2,
			sid:    22,
		},
		uc{
			dbname: "qejrmcwypi",
			tbname: "nslys",
			pk:     "vstpjucc",
			pid:    32,
			sid:    5,
		},
		uc{
			dbname: "rttczfqohf",
			tbname: "pgsor",
			pk:     "limnzkpi",
			pid:    26,
			sid:    6,
		},
		uc{
			dbname: "tzdckwidqu",
			tbname: "pxdia",
			pk:     "eorffnsi",
			pid:    19,
			sid:    13,
		},
		uc{
			dbname: "lywatweini",
			tbname: "pixwr",
			pk:     "isrkptox",
			pid:    21,
			sid:    1,
		},
		uc{
			dbname: "pktqrvrkuo",
			tbname: "ehpvk",
			pk:     "gehvoiwx",
			pid:    15,
			sid:    32,
		},
		uc{
			dbname: "vbkellaiqs",
			tbname: "avber",
			pk:     "swmqletu",
			pid:    8,
			sid:    3,
		},
		uc{
			dbname: "idxstfpdpy",
			tbname: "rsgdg",
			pk:     "drczsyyq",
			pid:    13,
			sid:    11,
		},
		uc{
			dbname: "hwrjgwaqum",
			tbname: "mplaa",
			pk:     "iszcesfs",
			pid:    16,
			sid:    32,
		},
		uc{
			dbname: "azvdhtjhbi",
			tbname: "abqot",
			pk:     "vxxqptgw",
			pid:    6,
			sid:    21,
		},
		uc{
			dbname: "jzlmklsqwx",
			tbname: "powua",
			pk:     "mnricnet",
			pid:    12,
			sid:    3,
		},
		uc{
			dbname: "aeooharazd",
			tbname: "gjoja",
			pk:     "dkabvghl",
			pid:    20,
			sid:    3,
		},
		uc{
			dbname: "jvflmavzjs",
			tbname: "vpcxd",
			pk:     "smywmtct",
			pid:    5,
			sid:    20,
		},
		uc{
			dbname: "igbndxzmxr",
			tbname: "edntd",
			pk:     "wjfhxvev",
			pid:    23,
			sid:    14,
		},
		uc{
			dbname: "fccswqtbxa",
			tbname: "qdbdf",
			pk:     "bawnhlty",
			pid:    11,
			sid:    17,
		},
		uc{
			dbname: "ulehkyoqke",
			tbname: "qiedu",
			pk:     "cqjlnlca",
			pid:    26,
			sid:    7,
		},
		uc{
			dbname: "heyxzqcsmf",
			tbname: "uwdil",
			pk:     "jcfxeyhf",
			pid:    10,
			sid:    7,
		},
		uc{
			dbname: "gravzxsxfj",
			tbname: "evepk",
			pk:     "muihkuon",
			pid:    0,
			sid:    11,
		},
		uc{
			dbname: "brfcivxndo",
			tbname: "xcung",
			pk:     "ilyoejkf",
			pid:    7,
			sid:    26,
		},
		uc{
			dbname: "jbihlvqpzg",
			tbname: "dsthj",
			pk:     "jgxhbiaa",
			pid:    25,
			sid:    14,
		},
		uc{
			dbname: "frhipxqzha",
			tbname: "phcno",
			pk:     "vsrvwykr",
			pid:    19,
			sid:    30,
		},
		uc{
			dbname: "slczxwtcyi",
			tbname: "lxcsy",
			pk:     "yysjrmnt",
			pid:    23,
			sid:    0,
		},
		uc{
			dbname: "imeubluzca",
			tbname: "ppkwa",
			pk:     "plxyrvof",
			pid:    1,
			sid:    9,
		},
		uc{
			dbname: "fbdvbjjqdu",
			tbname: "zvxxc",
			pk:     "ruejsqbl",
			pid:    20,
			sid:    15,
		},
		uc{
			dbname: "bkgavhtjoc",
			tbname: "agrok",
			pk:     "mydmrhuh",
			pid:    3,
			sid:    9,
		},
		uc{
			dbname: "geyqzkwcql",
			tbname: "fdtyl",
			pk:     "ubagojpz",
			pid:    29,
			sid:    24,
		},
		uc{
			dbname: "ljygwnowfn",
			tbname: "ydjnp",
			pk:     "waucgcgv",
			pid:    8,
			sid:    29,
		},
		uc{
			dbname: "idqztsccow",
			tbname: "lqjmt",
			pk:     "adaxvdqc",
			pid:    18,
			sid:    1,
		},
		uc{
			dbname: "flddgpdidu",
			tbname: "qkaoy",
			pk:     "ktmhvhcd",
			pid:    27,
			sid:    1,
		},
		uc{
			dbname: "ykvaawqzjc",
			tbname: "ogpas",
			pk:     "jvgvrdti",
			pid:    0,
			sid:    0,
		},
		uc{
			dbname: "swrtmkqjid",
			tbname: "bdlwu",
			pk:     "dktmcatr",
			pid:    27,
			sid:    15,
		},
		uc{
			dbname: "xaadbdiiqy",
			tbname: "ishut",
			pk:     "trrbctkj",
			pid:    25,
			sid:    9,
		},
		uc{
			dbname: "exgawbewyr",
			tbname: "ivzlf",
			pk:     "awvpinlx",
			pid:    14,
			sid:    7,
		},
		uc{
			dbname: "ixjnfhzvbg",
			tbname: "frvxt",
			pk:     "bvuzvsgn",
			pid:    3,
			sid:    26,
		},
		uc{
			dbname: "fsnbyemekx",
			tbname: "ytahh",
			pk:     "joglztsh",
			pid:    6,
			sid:    4,
		},
		uc{
			dbname: "hsvczaxsbz",
			tbname: "qwokf",
			pk:     "ucltrmiu",
			pid:    22,
			sid:    9,
		},
		uc{
			dbname: "uzzgrzveck",
			tbname: "rnpln",
			pk:     "ndkxbuad",
			pid:    24,
			sid:    4,
		},
		uc{
			dbname: "pehyshzzdu",
			tbname: "xomrr",
			pk:     "clmtlpyt",
			pid:    32,
			sid:    18,
		},
		uc{
			dbname: "dpshqeqlbx",
			tbname: "qhkie",
			pk:     "rwumcdnf",
			pid:    30,
			sid:    2,
		},
		uc{
			dbname: "ujytcnbgqc",
			tbname: "ncfja",
			pk:     "jouqslfs",
			pid:    20,
			sid:    24,
		},
		uc{
			dbname: "aynkiatskc",
			tbname: "gjeac",
			pk:     "nnfvifde",
			pid:    2,
			sid:    15,
		},
		uc{
			dbname: "unuoxswpzy",
			tbname: "hjnnm",
			pk:     "tdkpguuc",
			pid:    17,
			sid:    28,
		},
		uc{
			dbname: "fgyaikyamn",
			tbname: "bgfwd",
			pk:     "ohixdwdl",
			pid:    7,
			sid:    30,
		},
		uc{
			dbname: "ipgfwgltgw",
			tbname: "tdaxh",
			pk:     "qkvjljxc",
			pid:    13,
			sid:    27,
		},
		uc{
			dbname: "myyyoiwhfb",
			tbname: "krvhr",
			pk:     "owovqwlm",
			pid:    5,
			sid:    6,
		},
		uc{
			dbname: "muggurjder",
			tbname: "mreim",
			pk:     "oachmwtl",
			pid:    32,
			sid:    28,
		},
		uc{
			dbname: "hpqkjbproy",
			tbname: "ogshx",
			pk:     "avsomory",
			pid:    12,
			sid:    27,
		},
		uc{
			dbname: "hpsifgbict",
			tbname: "qalmi",
			pk:     "wdvargkz",
			pid:    11,
			sid:    1,
		},
		uc{
			dbname: "ozfjlhonho",
			tbname: "bcovh",
			pk:     "upsslxsy",
			pid:    27,
			sid:    1,
		},
		uc{
			dbname: "mmejftrmlu",
			tbname: "gqdic",
			pk:     "wwzmgiqw",
			pid:    30,
			sid:    27,
		},
		uc{
			dbname: "girbshesbv",
			tbname: "qtcpc",
			pk:     "vlnyvtbo",
			pid:    26,
			sid:    9,
		},
	}
)

func TestGetPartitionId(t *testing.T) {
	for _, useCase := range useCases {
		result := GetPartitionId(useCase.dbname, useCase.tbname, NewLaserKeyFormat([]string{useCase.pk}, []string{}), 33)
		assert.Equal(t, useCase.pid, result)
	}
}

func TestGetShardId(t *testing.T) {
	for _, useCase := range useCases {
		partition := NewPartition(useCase.dbname, useCase.tbname, useCase.pid)
		result := getShardId(partition.GetPartitionHash(), 33)
		assert.Equal(t, useCase.sid, result)
	}
}
