# jenkins_secret 客户端秘钥
#
- name: copy config file 
  template:
    src: roles/laser_data_cleaner/templates/laser_data_cleaner.sh
    dest: /usr/local/adbot/{{instance_name}}/laser_data_cleaner.sh
    owner: adbot
    group: adbot
    mode: 0644
  tags:
    - upgrade
- name: create laser data cleaner cron.d file 
  become: yes
  cron:
    name: "laser clean data"
    user: "adbot"
    job: ". /etc/bashrc;/bin/sh /usr/local/adbot/{{instance_name}}/laser_data_cleaner.sh >> /usr/local/adbot/{{instance_name}}/logs/{{instance_name}}_clean_data.log"
    cron_file: "ansible_{{instance_name}}_data_cleaner"
    minute: "{{clean_minute}}"
    hour: "{{clean_hour}}"
  tags:
    - upgrade
- name: clean partition data
  script: partition_cleaner.py -host={{ansible_all_ipv4_addresses[0]}} -port={{http_port}} -node-dir=/usr/local/adbot/{{instance_name}}/data/data/{{group_name}}/{{node_id}} -dest-dir=/usr/local/adbot/tmp > /tmp/partition_cleaner.info
  args:
    executable: python
  tags:
    - clean_data
- name: clean partition metadata
  shell: curl -X POST 'http://{{ansible_all_ipv4_addresses[0]}}:{{http_port}}/clean/partitions'
  args:
    warn: false
  tags:
    - clean_metadata 
