debug: false
static:
  root: ./
http:
  port: 8083
  host: 0.0.0.0
database:
  driver: sqlite3
  dsn: /tmp/laser_control.db
logger:
  level: debug
  fileName: ./logs/service.log
  maxSize: 1024
  maxBackups: 3
  maxAge: 7
  compress: true
auth:
  sessionSaveSeconds: 86400
consul:
  address: # your consul address
  scheme : http
  token: # your consul token
cluster:
  serviceName: test_inner
  proxyServiceName: test_inner
project:
  projectName: test
laserClient:
  timeoutMs:  10000
batchUpdateManager:
  url: # http://IP:Port
ansible:
  sshPort: 22
  playbookDir: ./tmp
  tmpHostFile: hosts
  tmpPlaybookFile: playbook.yml
email:
  emailUser: # user
  emailPassword: # password
  emailSnmpAddress: # address
  emailFrom: # email_account
report:
  cronExpressionPeak: "0 0 23 * * *"
  cronExpressionPeacePeak: "0 0 12 * * * *"
prometheus:
  serverPrometheusAddress: # prometheus address for laser server running info
  clientPrometheusAddress: # prometheus address for machine physical resource
commonUrls:
  - /database/list
  - /keycheck/list
  - /version_change/show
  - /table/list
  - /table/list_commands
  - /ticket/store
  - /ticket/list
  - /ticket/update
  - /user/info
  - /config_validator/unsynchronized_config
adminUsers:
  - admin
laserCommands:
  singleOperations:
    - get
    - set
    - expire
    - expireAt
    - ttl
    - append
    - setx
    - exist
    - hget
    - hgetall
    - hexists
    - hkeys
    - hlen
    - hmget
    - hset
    - hmset
    - hdel
    - decr
    - incr
    - decrBy
    - incrBy
    - lindex
    - llen
    - lpop
    - lpush
    - lrange
    - rpop
    - rpush
    - sadd
    - sismember
    - sremove
    - smembers
    - zadd
    - zrangeByScore
    - zremRangeByScore
  multipleOperations:
    - mset
    - mget
    - msetDetail
    - mgetDetail
